// app/javascript/controllers/index.js
// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FormSubmitController from "./form_submit_controller"
application.register("form-submit", FormSubmitController)

import HabitCheckboxController from "./habit_checkbox_controller"
application.register("habit-checkbox", HabitCheckboxController)

import HabitFormController from "./habit_form_controller"
application.register("habit-form", HabitFormController)

import HabitMenuController from "./habit_menu_controller"
application.register("habit-menu", HabitMenuController)

import HabitRecordController from "./habit_record_controller"
application.register("habit-record", HabitRecordController)

import HabitSortController from "./habit_sort_controller"
application.register("habit-sort", HabitSortController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

// ── B-7 追加: voice-input コントローラーを登録する ──────────────────────────
//
// 【なぜ手動で登録するのか】
//   Rails の stimulus:manifest:update コマンドは controllers/ 配下の
//   ファイルを自動検出して index.js を更新する。
//   ただし、コマンドを手動実行するまで反映されないため、
//   ここに手動で追記しておく。
//   次回 stimulus:manifest:update を実行すると自動で整理される。
//
// 【登録名 "voice-input" について】
//   HTML 側の data-controller="voice-input" と対応する。
//   キャメルケースのファイル名（VoiceInputController）が
//   ケバブケース（voice-input）に変換されてHTMLの属性名になる。
import VoiceInputController from "./voice_input_controller"
application.register("voice-input", VoiceInputController)

// ── C-1 追加: priority-card コントローラーを登録する ─────────────────────────
//
// 【このコントローラーの役割】
//   タスク作成フォームの優先度カード（Must/Should/Could）の
//   選択状態をビジュアルで切り替える。
import PriorityCardController from "./priority_card_controller"
application.register("priority-card", PriorityCardController)

// ── C-2 追加: task-toggle コントローラーを登録する ───────────────────────────
//
// 【このコントローラーの役割】
//   タスクの完了チェックボックスをクリックしたとき、
//   Turbo Stream でページリロードなしに status を切り替える。
//
// 【登録名 "task-toggle" について】
//   HTML 側の data-controller="task-toggle" と対応する。
//   ファイル名 task_toggle_controller.js が
//   ケバブケース task-toggle に変換されてHTMLの属性名になる。
import TaskToggleController from "./task_toggle_controller"
application.register("task-toggle", TaskToggleController)