// app/javascript/controllers/index.js
// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AiAnalysisPollingController from "./ai_analysis_polling_controller"
application.register("ai-analysis-polling", AiAnalysisPollingController)

import AiLimitModalController from "./ai_limit_modal_controller"
application.register("ai-limit-modal", AiLimitModalController)

import AiProposalModalController from "./ai_proposal_modal_controller"
application.register("ai-proposal-modal", AiProposalModalController)

import AiThrottleController from "./ai_throttle_controller"
application.register("ai-throttle", AiThrottleController)

import AlarmToggleController from "./alarm_toggle_controller"
application.register("alarm-toggle", AlarmToggleController)

import CrisisInterventionController from "./crisis_intervention_controller"
application.register("crisis-intervention", CrisisInterventionController)

import DeactivateModalController from "./deactivate_modal_controller"
application.register("deactivate-modal", DeactivateModalController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FormSubmitController from "./form_submit_controller"
application.register("form-submit", FormSubmitController)

import HabitCheckboxController from "./habit_checkbox_controller"
application.register("habit-checkbox", HabitCheckboxController)

import HabitFormController from "./habit_form_controller"
application.register("habit-form", HabitFormController)

import HabitMenuController from "./habit_menu_controller"
application.register("habit-menu", HabitMenuController)

import HabitRecordController from "./habit_record_controller"
application.register("habit-record", HabitRecordController)

import HabitSortController from "./habit_sort_controller"
application.register("habit-sort", HabitSortController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import MoodRatingController from "./mood_rating_controller"
application.register("mood-rating", MoodRatingController)

import NotificationLimitController from "./notification_limit_controller"
application.register("notification-limit", NotificationLimitController)

import PriorityCardController from "./priority_card_controller"
application.register("priority-card", PriorityCardController)

// G-4 追加: お休みモード確認モーダルコントローラー
// rest_mode_modal_controller.js が存在するにもかかわらず
// stimulus:manifest:update で自動登録されなかった場合は手動で追記する
import RestModeModalController from "./rest_mode_modal_controller"
application.register("rest-mode-modal", RestModeModalController)

import TaskMenuController from "./task_menu_controller"
application.register("task-menu", TaskMenuController)

import TaskToggleController from "./task_toggle_controller"
application.register("task-toggle", TaskToggleController)

import TermsAgreementController from "./terms_agreement_controller"
application.register("terms-agreement", TermsAgreementController)

import VoiceInputController from "./voice_input_controller"
application.register("voice-input", VoiceInputController)