// app/javascript/controllers/index.js
// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AiAnalysisPollingController from "./ai_analysis_polling_controller"
application.register("ai-analysis-polling", AiAnalysisPollingController)

import AiLimitModalController from "./ai_limit_modal_controller"
application.register("ai-limit-modal", AiLimitModalController)

import AiProposalModalController from "./ai_proposal_modal_controller"
application.register("ai-proposal-modal", AiProposalModalController)

import AiThrottleController from "./ai_throttle_controller"
application.register("ai-throttle", AiThrottleController)

import AlarmToggleController from "./alarm_toggle_controller"
application.register("alarm-toggle", AlarmToggleController)

import CrisisInterventionController from "./crisis_intervention_controller"
application.register("crisis-intervention", CrisisInterventionController)

import DeactivateModalController from "./deactivate_modal_controller"
application.register("deactivate-modal", DeactivateModalController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FormSubmitController from "./form_submit_controller"
application.register("form-submit", FormSubmitController)

import HabitCheckboxController from "./habit_checkbox_controller"
application.register("habit-checkbox", HabitCheckboxController)

import HabitFormController from "./habit_form_controller"
application.register("habit-form", HabitFormController)

import HabitMenuController from "./habit_menu_controller"
application.register("habit-menu", HabitMenuController)

import HabitRecordController from "./habit_record_controller"
application.register("habit-record", HabitRecordController)

import HabitSortController from "./habit_sort_controller"
application.register("habit-sort", HabitSortController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import MoodRatingController from "./mood_rating_controller"
application.register("mood-rating", MoodRatingController)

import NotificationLimitController from "./notification_limit_controller"
application.register("notification-limit", NotificationLimitController)

// G-3 修正: 通知全般マスタースイッチの連動コントローラー
import NotificationMasterController from "./notification_master_controller"
application.register("notification-master", NotificationMasterController)

import PriorityCardController from "./priority_card_controller"
application.register("priority-card", PriorityCardController)

// G-4 追加: お休みモード確認モーダルコントローラー
import RestModeModalController from "./rest_mode_modal_controller"
application.register("rest-mode-modal", RestModeModalController)

// G-6 追加: 設定ページのプロフィール編集インライン制御コントローラー
// 【なぜ手動登録するのか】
//   stimulus:manifest:update は自動生成だが、
//   ファイル追加後に実行し忘れることがある。
//   明示的に登録することで確実に動作する。
import SettingsProfileController from "./settings_profile_controller"
application.register("settings-profile", SettingsProfileController)

import TaskMenuController from "./task_menu_controller"
application.register("task-menu", TaskMenuController)

import TaskToggleController from "./task_toggle_controller"
application.register("task-toggle", TaskToggleController)

import TermsAgreementController from "./terms_agreement_controller"
application.register("terms-agreement", TermsAgreementController)

import VoiceInputController from "./voice_input_controller"
application.register("voice-input", VoiceInputController)

// G-7 追加: バナーを×ボタンで非表示にする汎用コントローラー
// 【なぜ手動登録するのか】
//   stimulus:manifest:update は自動生成だが、
//   ファイル追加後に実行し忘れることがある。
//   明示的に登録することで確実に動作する。
import DismissibleController from "./dismissible_controller"
application.register("dismissible", DismissibleController)

// H-4 追加: グラフ・進捗分析ページのChart.js描画コントローラー
// 【なぜ手動登録するのか】
//   stimulus:manifest:update は自動生成だが、
//   ファイル追加後に実行し忘れることがある。
//   明示的に登録することで確実に動作する。
import AnalyticsChartController from "./analytics_chart_controller"
application.register("analytics-chart", AnalyticsChartController)

// H-5追加: オンボーディング習慣テンプレート選択コントローラー
import OnboardingTemplateController from "./onboarding_template_controller"
application.register("onboarding-template", OnboardingTemplateController)
