require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # In the development environment your application's code is reloaded any time
  # it changes. This slows down response time but is perfect for development
  # since you don't have to restart the web server when you make code changes.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable caching. By default caching is disabled.
  # Run rails dev:cache to toggle caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true

    config.cache_store = :memory_store
    config.public_file_server.headers = { "Cache-Control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false

    config.cache_store = :null_store
  end

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # ============================================================
  # Issue #A-4: 開発環境のメール設定（letter_opener_web）
  # ============================================================
  #
  # 【なぜ letter_opener_web を使うのか】
  #   開発中に Resend で実際にメールを送信すると:
  #     1. 無料枠（月3,000通）を無駄に消費する
  #     2. 実在するアドレスに誤ってメールが届く危険がある
  #     3. テストのたびにメールボックスを確認する手間がかかる
  #
  #   letter_opener_web を使うと:
  #     - deliver_now / deliver_later を呼んだとき実際には送信しない
  #     - http://localhost:3000/letter_opener にアクセスするだけで
  #       送信済みメールの一覧・内容を確認できる Web UI が使える
  #     - 件名・本文・HTMLの見た目を即座に確認できる
  #     - 開発スピードが大幅に向上する
  #
  # 【なぜ :letter_opener ではなく :letter_opener_web を使うのか】
  #   :letter_opener     → 送信のたびに新しいブラウザタブを自動で開こうとする。
  #                        Docker コンテナ内にはブラウザが存在しないため開かれない。
  #   :letter_opener_web → /letter_opener にアクセスして一覧で確認できる。
  #                        Docker 環境での開発に最適。
  config.action_mailer.delivery_method = :letter_opener_web

  # メールURLのドメイン設定（開発環境用）
  # localhost:3000 でアクセスするため、そのまま指定する
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # 送信失敗時にエラーを出さない
  # （letter_opener_web は常に成功するため不要）
  config.action_mailer.raise_delivery_errors = false

  # メールテンプレートのキャッシュは無効（変更を即座に反映するため）
  config.action_mailer.perform_caching = false

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise exceptions for disallowed deprecations.
  config.active_support.disallowed_deprecation = :raise

  # Tell Active Support which deprecation messages to disallow.
  config.active_support.disallowed_deprecation_warnings = []

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
  # ============================================================
  # Issue #29: Bullet gem の設定（N+1問題の検出）
  # ============================================================
  # Bulletは開発中にN+1問題やEager Loadingの過不足を自動検出し、
  # ログやブラウザのアラートで知らせてくれます。
  #
  # 【設定項目の説明】
  # bullet.enable         → Bulletの機能をONにする
  # bullet.alert          → N+1を検出したらブラウザのアラートで通知する
  # bullet.rails_logger   → RailsのログにN+1の警告を出力する
  # bullet.add_footer     → 画面の下部にN+1の警告を小さく表示する
  config.after_initialize do
    Bullet.enable        = true   # Bullet全体のON/OFF
    Bullet.alert         = true   # ブラウザのポップアップアラートで通知
    Bullet.rails_logger  = true   # ターミナルのRailsログに警告を出力
    Bullet.add_footer    = true   # 画面下部にN+1警告を小さく表示
  end

  # ============================================================
  # Issue #A-3: 開発環境の GoodJob execution_mode 設定
  # ============================================================
  #
  # 【なぜ :async にするのか】
  # :async モード: Rails の Web プロセス内でバックグラウンドスレッドを起動して
  #               ジョブを実行する。Docker 1台で Web と Worker が同居するイメージ。
  #
  # :external モード: 別プロセス（bundle exec good_job start）が必要。
  #                  将来 Render 有料プランに移行して Worker を分離する場合向けの設定。
  #                  現在の本番環境（Render Free プラン）でも :async を使用している。
  #
  # 開発環境で :external を使うと、Worker を別途起動しない限り
  # ジョブが「Queued」のまま実行されない（ダッシュボードで確認できた症状）。
  # :async にすることで docker compose up だけで即座にジョブが実行される。
  config.good_job.execution_mode = :async

  # =========================================================================
  # Turbo CSS preload 警告の抑制（開発環境限定）
  # =========================================================================
  # 【なぜ development.rb に書くのか】
  #   config/application.rb に書くと本番・テスト環境にも影響する。
  #   開発コンソールの警告のみ解消したいため development 限定にする。
  #
  # 【何を防ぐか】
  #   Rails 7.2 + Turbo 環境では stylesheet_link_tag が
  #   HTTP レスポンスヘッダーに Link: rel=preload を自動付与する。
  #   Turbo のページ遷移では CSS がすでに読み込み済みのため
  #   ブラウザが「使われなかった preload」として警告を出す。
  #
  # 【なぜ respond_to? で条件分岐するのか】
  #   Rails のバージョンによって preload_links_header= が存在しない場合がある。
  #   respond_to? で存在確認してから呼ぶことで
  #   将来の Rails アップデート時も安全に動作する。
  #
  # 【画面・スタイルへの影響】
  #   なし。CSS は HTML の <link rel="stylesheet"> タグで引き続き読み込まれる。
  # =========================================================================
  if config.action_view.respond_to?(:preload_links_header=)
    config.action_view.preload_links_header = false
  end
end